config/routes.rb
Rails.application.routes.draw do
  #root
  resources :welcome, only: [:index, :create]
  root "welcome#index"
  #users
  resources :users, only: [:new, :create]
  #url info
  resources :urls, only: [:index, :show]
  #tiny_url_slug
  get ':tiny_url' => 'urls#show'
  #sessions for 2factorauthentication
  resources :sessions, only: [:new, :create]
  get "sessions/destroy"
  get "sessions/two_factor"
  post "sessions/verify"
  post "sessions/resend"
  # User account section for 2factorauthentication
  # resources :accounts, only: [:show]
  #api
  namespace :api do
    namespace :v1 do
      resources :urls
    end
  end
end

app/models/url.rb
require 'time'

class Url < ActiveRecord::Base
  belongs_to :user

  validates :original_url, presence: true
  validates_format_of :original_url, :with => /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix

  def generate_tiny_url
    self.tiny_url = self.id.to_s(36)
    # self.tiny_url = SecureRandom.urlsafe_base64(5)
    self.save
  end

  def display_tiny_url
    ENV["BASE_URL"] + "#{self.tiny_url}"
  end

  def time
    time = self.created_at.strftime("%b %e, %l:%M %p")
  end

  def self.popularity_sort
    all.order(clicks: :desc)
  end

  def self.date_sort
    all.order(created_at: :desc)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :urls

  validates :email, presence: true, format: { with: /\A.+@.+$\Z/ }, uniqueness: true
  validates :first_name, :last_name, :password, :phone, presence: true
  validates :country_code, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/api/v1/urls_controller.rb
class Api::V1::UrlsController < ApplicationController
  respond_to :html, :json, :xml

  def index
    @urls = Url.all
    respond_with @urls
  end

  def show
    @url = Url.find(params[:id])
    respond_with @url
  end

  def create
    @url = Url.create(url_params)
    respond_with @url
  end

  def update
    @url = Url.update(params[:id], url_params)
    respond_with @url
  end

  def destroy
    @url = Url.destroy(params[:id])
    respond_with @url
  end

  private

  def url_params
    params.require(:url).permit(:original_url, :tiny_url, :clicks)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def signed_in?
    current_user.present?
  end
  helper_method :signed_in?

  protected

  def authenticate!
    redirect_to new_session_path, alert: "Please login to see our most popular urls" and return unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:pre_2fa_auth_user_id] = @user.id
      Authy::API.request_sms(id: @user.authy_id)
      redirect_to sessions_two_factor_path
    else
      @user ||= User.new(email: params[:email])
      render :new
    end
  end

  def two_factor
    return redirect_to new_session_path unless session[:pre_2fa_auth_user_id]
  end

  def verify
    @user = User.find(session[:pre_2fa_auth_user_id])
    token = Authy::API.verify(id: @user.authy_id, token: params[:token])
    if token.ok?
      session[:user_id] = @user.id
      session[:pre_2fa_auth_user_id] = nil
      redirect_to urls_path
    else
      flash.now[:danger] = "Incorrect code, please try again"
      render :two_factor
    end
  end

  def resend
    @user = User.find(session[:pre_2fa_auth_user_id])
    Authy::API.request_sms(id: @user.authy_id)
    flash[:notice] = "Verification code re-sent"
    redirect_to sessions_two_factor_path
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out"
    redirect_to root_path
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate!, :except => [:show]

  def index
    # @user = current_user
    @urls = Url.where(nil)
    sorting_params(params).each do |key, value|
      @urls = @urls.public_send(key)
    end
  end

  def show
    # if params[:tiny_url]
    @url = Url.find_by(tiny_url: (params[:tiny_url]))
    # else
    #   @url = Url.find(params[:id])
    # end
    @url.clicks += 1
    @url.save
    redirect_to @url.original_url
  end

  def sorting_params(params)
    params.slice(:popularity_sort, :date_sort)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      authy = Authy::API.register_user(
        email: @user.email,
        cellphone: @user.phone,
        country_code: @user.country_code
      )
      @user.update(authy_id: authy.id)
      redirect_to root_path(current_user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :phone,
                                 :password,
                                 :country_code,
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tiny_url = params[:tiny_url]
    @original_url = params[:original_url]
  end

  def create
    @url = Url.new(original_url: params[:url], clicks: 0)
    if @url.save
      @url.generate_tiny_url
      redirect_to :action => 'index', :params => { :tiny_url => @url.display_tiny_url, :original_url => @url.original_url }
    else
      redirect_to welcome_index_path, alert: "Please enter a valid URL"
    end
  end

end

app/helpers/api/v1/urls_helper.rb
module Api::V1::UrlsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
        message
      end)
    end
    nil
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JetFuel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="https://www.authy.com/form.authy.min.css" media="screen" rel="stylesheet" type="text/css">
  <script src="https://www.authy.com/form.authy.min.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="main" class="container">
    <nav class="navbar navbar-default">
      <a class="navbar-brand" href="/">Mini-Urls</a>
      <p id="nav-links" class="navbar-text pull-right">
        <% if signed_in? %>
          Welcome back <%= link_to current_user.full_name, sessions_path %>!
          <%= link_to "Log out", sessions_destroy_path %>
        <% else %>
          <%= link_to "Sign Up", new_user_path %> or
          <%= link_to "Log in", new_session_path %>
        <% end -%>
      </p>
    </nav>
    <%= flash_messages %>
    <%= yield %>
  </section>
</body>
</html>

app/views/urls/index.html.erb
<a class="Home" href="/">Home</a>
	<div class="url-header">
	<h1>URL Index</h1>
</div>

<div class="filter">
	<%= text_field_tag :original_url %>
	<%= submit_tag "Filter by Original URL", id: "filter-urls", class: "btn btn-default filter"%>
</div>

<div class="all-links">
	<table class="center" id="t01">
	  <tr>
	    <th>Original URL</th>
	    <th>Mini URL</th>
			<th><%= link_to "Views", urls_path(popularity_sort: "hi") %></th>
	    <th><%= link_to "Day/Time Created", urls_path(date_sort: "ho") %></th>
	  </tr>
	  <tr>
		<% @urls.each do |url|%>
			<td><%= truncate(url.original_url, length: 50, omission: '... (et cetera)', escape: false) %></td>
	    <!-- <td><%#= link_to url.display_tiny_url, url_path(url.id) %></td> -->
			<td><%= link_to url.display_tiny_url, url.original_url %></td>
	    <td><%= url.clicks %></td>
	    <td><%= url.time %></td>
	  </tr>
		<% end %>
	</table>
</div>

app/views/users/new.html.erb
<h1>We're going to be *BEST* friends</h1>
<p> Thanks for your interest in signing up! Can you tell us a bit about yourself?</p>

<% if @user.errors.any? %>
  <h2>Oops, something went wrong!</h2>

  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end -%>
  </ul>
<% end -%>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :first_name, "Tell us your name:" %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, "Tell us your name:" %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Enter Your E-mail Address:" %>
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Enter a password:" %>
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="form-group">
    <%= f.label :country_code %>
    <%= f.text_field :country_code, class: "form-control", id: "authy-countries" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone, class: "form-control", id: "authy-cellphone" %>
  </div>
  <button class="btn btn-primary">Sign up</button>
<% end -%>

app/views/welcome/index.html.erb
<div class='container url-home' id="url1">
  <h1>
    <%= form_tag("/welcome", method: "create") do %>
    <%= label_tag("Which url do you want shortened?") %><br>
  </h1>
  <h2>
    <%= text_field_tag "url", "URL must include http:// or https://",
    :onclick => 'if($(this).val()=="URL must include http:// or https://"){$(this).val("");};' %><br><br>
  </h2>
  <button id="Shorten" type="submit" class="btn btn-lg btn-primary">Shorten my url!</button><br><br>
  <% end %>
</div>
<row>
  <div class="mini col-md-4">
    <%= image_tag "mini.jpg" %>
  </div>
  <h1>
  <div class="tiny_url col-md-8">
    I shall call it: <br>
    <div class="yo"> <a href="<%=@original_url%>"><br><%= @tiny_url %></a><br><br><br>
    </div>
    <a href= "/urls"><button class="btn btn-lg btn-primary">See most popular Mini-Urls</button></a>
  </div>
  </h1>
</row>